name: Bug Report or Feature Request
description: File a bug report or request a new feature.
title: "[Bug?]: "
labels: ["bug", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to file an issue!
        
        If you have a bug or feature request, please specify the expected input and output in the form of a failing Jest test:


        ```ts failing test
        expect(
          emotionToVanillaExtract({
            border: "1px solid red",
          }),
        ).toMatchInlineSnapshot(`
          "{
            "border": "1px solid red",
          }"
        `);
  - type: textarea
    id: failing-test
    attributes:
      label: Failing test
      description: What is the desired input and output you would like, that is not currently working or supported.
      value: |
        ```ts failing test
        expect(
          emotionToVanillaExtract({
            border: "1px solid red",
          }),
        ).toMatchInlineSnapshot(`
          "{
            "border": "1px solid red",
          }"
        `);
        ```
    validations:
      required: true
  - type: textarea
    id: info
    attributes:
      label: Any other info?
